apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs
        image: gunasagaransureshsg/nodejs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
